/* The JS keeper implementation against the SHARED vectors.
 *
 * These vectors are generated by Python (draft/gen_keeper_vectors.py) and
 * asserted by both suites. That is the whole point: two implementations of the
 * same maths is how you get a divergence that corrupts every pick number while
 * both sides look healthy. If this file goes red, do not "fix" it by editing
 * the expectations — regenerate the vectors and check which side actually moved.
 *
 * Run: node draft/tests/keepers.test.js
 */
const fs = require('fs');
const path = require('path');
const K = require('../../public/js/draft/keepers.js');

const V = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'fixtures', 'keeper_vectors.json'), 'utf8'));

let pass = 0, fail = 0;
function check(name, cond, detail) {
  if (cond) { pass++; console.log('PASS  ' + name); }
  else { fail++; console.log('FAIL  ' + name + (detail ? '\n      -> ' + detail : '')); }
}

V.cases.forEach(c => {
  const label = c.name;
  const order = K.buildTruePickOrder(c.cfg, c.keepers);
  const e = c.expect;

  check(`[${label}] pick count matches Python`,
    order.picks.length === e.pick_count, `${order.picks.length} vs ${e.pick_count}`);

  const gotForfeit = order.forfeited.map(f => [f.team_slot, f.cost_round])
    .sort((a, b) => a[0] - b[0] || a[1] - b[1]);
  check(`[${label}] forfeited picks match Python`,
    JSON.stringify(gotForfeit) === JSON.stringify(e.forfeited),
    `${JSON.stringify(gotForfeit)} vs ${JSON.stringify(e.forfeited)}`);

  check(`[${label}] my pick numbers match Python`,
    JSON.stringify(order.my_picks) === JSON.stringify(e.my_picks),
    `${JSON.stringify(order.my_picks)} vs ${JSON.stringify(e.my_picks)}`);

  check(`[${label}] pre-keeper pick numbers match Python`,
    JSON.stringify(order.my_original_picks) === JSON.stringify(e.my_original_picks));

  const keptIds = [];
  Object.keys(c.keepers).forEach(s => (c.keepers[s] || []).forEach(k => keptIds.push(String(k.player_id))));
  const adj = K.adjustedAdp(V.players, order, c.cfg, keptIds);

  const mismatches = [];
  adj.forEach(p => {
    const want = e.adjusted_adp[p.player_id];
    if (want == null) { mismatches.push(`${p.player_id} unexpected in JS pool`); return; }
    if (Math.abs(p.adjusted_adp - want) > 1e-9) {
      mismatches.push(`${p.player_id}: js=${p.adjusted_adp} py=${want}`);
    }
    if (p.pool_rank !== e.pool_rank[p.player_id]) {
      mismatches.push(`${p.player_id} rank: js=${p.pool_rank} py=${e.pool_rank[p.player_id]}`);
    }
  });
  check(`[${label}] every adjusted ADP and pool rank matches Python exactly`,
    mismatches.length === 0 && adj.length === Object.keys(e.adjusted_adp).length,
    mismatches.slice(0, 5).join('; ') || `count js=${adj.length} py=${Object.keys(e.adjusted_adp).length}`);
});

// --- behaviours the vectors alone would not pin down ------------------------

/* REMOVING ANOTHER TEAM'S KEEPER MUST NOT MOVE MY PICKS — AND THIS BLOCK
 * ASSERTED THE OPPOSITE UNTIL 2026-08-13.
 *
 * Its comment read "Removing one keeper must shift EVERY downstream pick, not
 * just that team's", and `buildTruePickOrder` renumbered the survivors 1..N to
 * make that true. Sleeper's own log for this league says otherwise: 150 picks
 * and round 4 beginning at overall 31 in 2023 (0 keepers), 2024 (23) and 2025
 * (20) alike. A keeper OCCUPIES his pick; dropping him converts a keeper slot
 * into a live selection and moves no board number at all. */
{
  const c = V.cases[0];
  const before = K.buildTruePickOrder(c.cfg, c.keepers);
  const trimmed = JSON.parse(JSON.stringify(c.keepers));
  trimmed['1'] = trimmed['1'].slice(1);          // team 1 keeps one fewer
  const after = K.buildTruePickOrder(c.cfg, trimmed);
  check('removing one keeper adds a SELECTION to the draft',
    after.picks.length === before.picks.length + 1,
    `${before.picks.length} -> ${after.picks.length}`);
  check('but the BOARD is the same size — a forfeited pick is occupied, not deleted',
    after.board.length === before.board.length
    && after.board.length === c.cfg.teams * c.cfg.rounds,
    `${before.board.length} -> ${after.board.length}`);
  check('one fewer slot is flagged as keeper-occupied',
    after.board.filter(p => p.keeper_slot).length
    === before.board.filter(p => p.keeper_slot).length - 1);
  check('and removing ANOTHER team\'s keeper leaves MY pick numbers alone',
    JSON.stringify(after.my_picks) === JSON.stringify(before.my_picks),
    `${before.my_picks.slice(0, 5)} vs ${after.my_picks.slice(0, 5)}`);
  check('CONTROL — team 1 is not me, so the change really did land elsewhere',
    Number(c.cfg.my_draft_slot) !== 1, c.cfg.my_draft_slot);
}

// The roll-forward rule for two keepers costing the same round is easy to lose
// in a port and would quietly shift everything after it.
{
  const cfg = { teams: 10, rounds: 8, draft_type: 'snake', roster_size: 11,
                my_draft_slot: 1, adp_blend_weight: 0.7,
                keepers: { count: 2, cost_model: 'original_round', undrafted_round: 10 } };
  const o = K.buildTruePickOrder(cfg, { 3: [{ player_id: 'a', original_round: 2 },
                                            { player_id: 'b', original_round: 2 }] });
  const rounds = o.forfeited.map(f => f.cost_round).sort();
  check('two keepers on the same round roll forward instead of colliding',
    JSON.stringify(rounds) === '[2,3]', JSON.stringify(rounds));
}

// Changing only the slot must not change the pick SEQUENCE, only ownership.
{
  const c = V.cases[0];
  const a = K.buildTruePickOrder(Object.assign({}, c.cfg, { my_draft_slot: 2 }), c.keepers);
  const b = K.buildTruePickOrder(Object.assign({}, c.cfg, { my_draft_slot: 9 }), c.keepers);
  check('a slot change leaves the pick sequence identical',
    JSON.stringify(a.picks.map(p => p.overall)) === JSON.stringify(b.picks.map(p => p.overall)));
  check('a slot change does change which picks are mine',
    JSON.stringify(a.my_picks) !== JSON.stringify(b.my_picks));
  check('runtime slot change equals a rebuild at that slot',
    JSON.stringify(a.my_picks) === JSON.stringify(
      a.picks.filter(p => p.team_slot === 2).map(p => p.overall)));
}

// --- top_picks_flat: keeping N keepers forfeits rounds 1..N (JS↔Python parity) --
// This is the case the JS keeperCostRound used to miss — it fell through to
// original_round, so a keeper first drafted in a later round wrongly forfeited
// that later round instead of the flat top pick.
(function topPicksFlat() {
  const cfg = { teams: 10, rounds: 15, draft_type: 'snake', my_draft_slot: 4,
    keepers: { count: 3, cost_model: 'top_picks_flat', count_undrafted_round: 10 } };
  // Three keepers whose ORIGINAL rounds are all over the map (1, 5, 9). Under
  // top_picks_flat they must still forfeit rounds 1, 2, 3 — never 5 or 9.
  const keepers = { 4: [
    { player_id: 'a', name: 'A', original_round: 1 },
    { player_id: 'b', name: 'B', original_round: 5 },
    { player_id: 'c', name: 'C', original_round: 9 },
  ] };
  const order = K.buildTruePickOrder(cfg, keepers);
  const myForfeitRounds = order.forfeited.map(f => f.cost_round).sort((x, y) => x - y);
  check('top_picks_flat forfeits rounds 1,2,3 regardless of original round',
    JSON.stringify(myForfeitRounds) === JSON.stringify([1, 2, 3]),
    JSON.stringify(myForfeitRounds));
  // My first surviving pick is the round-4 pick, not round 1.
  const firstRound4Overall = 10 * 3 + (10 - cfg.my_draft_slot + 1); // snake R4 reversed: slot 4 -> 30+7=37 original
  check('my first pick lands in round 4 (top 3 forfeited)',
    order.my_picks.length === cfg.rounds - 3, order.my_picks.length + ' picks');
  // The MOCK OVER-ROSTER INVARIANT: keepers(3) + surviving my_picks(12) == rounds(15).
  // Before the fix the mock forfeited nothing, so it was 3 + 15 = 18 (over by 3).
  check('keepers + surviving picks == rounds (no over-roster)',
    keepers[4].length + order.my_picks.length === cfg.rounds,
    keepers[4].length + ' + ' + order.my_picks.length + ' vs ' + cfg.rounds);
})();

// Python's round() is banker's rounding. Naive JS rounding diverges on ties.
check('round2 matches Python banker\'s rounding on exact ties',
  K.round2(2.675) === 2.68 || K.round2(2.675) === 2.67,   // representable-dependent
  String(K.round2(2.675)));
check('round2(0.125) ties to even like Python', K.round2(0.125) === 0.12, String(K.round2(0.125)));

console.log(`\n${pass}/${pass + fail} keeper parity checks passed`);
process.exit(fail ? 1 : 0);
