/* The JS keeper implementation against the SHARED vectors.
 *
 * These vectors are generated by Python (draft/gen_keeper_vectors.py) and
 * asserted by both suites. That is the whole point: two implementations of the
 * same maths is how you get a divergence that corrupts every pick number while
 * both sides look healthy. If this file goes red, do not "fix" it by editing
 * the expectations — regenerate the vectors and check which side actually moved.
 *
 * Run: node draft/tests/keepers.test.js
 */
const fs = require('fs');
const path = require('path');
const K = require('../../public/js/draft/keepers.js');

const V = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'fixtures', 'keeper_vectors.json'), 'utf8'));

let pass = 0, fail = 0;
function check(name, cond, detail) {
  if (cond) { pass++; console.log('PASS  ' + name); }
  else { fail++; console.log('FAIL  ' + name + (detail ? '\n      -> ' + detail : '')); }
}

V.cases.forEach(c => {
  const label = c.name;
  const order = K.buildTruePickOrder(c.cfg, c.keepers);
  const e = c.expect;

  check(`[${label}] pick count matches Python`,
    order.picks.length === e.pick_count, `${order.picks.length} vs ${e.pick_count}`);

  const gotForfeit = order.forfeited.map(f => [f.team_slot, f.cost_round])
    .sort((a, b) => a[0] - b[0] || a[1] - b[1]);
  check(`[${label}] forfeited picks match Python`,
    JSON.stringify(gotForfeit) === JSON.stringify(e.forfeited),
    `${JSON.stringify(gotForfeit)} vs ${JSON.stringify(e.forfeited)}`);

  check(`[${label}] my pick numbers match Python`,
    JSON.stringify(order.my_picks) === JSON.stringify(e.my_picks),
    `${JSON.stringify(order.my_picks)} vs ${JSON.stringify(e.my_picks)}`);

  check(`[${label}] pre-keeper pick numbers match Python`,
    JSON.stringify(order.my_original_picks) === JSON.stringify(e.my_original_picks));

  const keptIds = [];
  Object.keys(c.keepers).forEach(s => (c.keepers[s] || []).forEach(k => keptIds.push(String(k.player_id))));
  const adj = K.adjustedAdp(V.players, order, c.cfg, keptIds);

  const mismatches = [];
  adj.forEach(p => {
    const want = e.adjusted_adp[p.player_id];
    if (want == null) { mismatches.push(`${p.player_id} unexpected in JS pool`); return; }
    if (Math.abs(p.adjusted_adp - want) > 1e-9) {
      mismatches.push(`${p.player_id}: js=${p.adjusted_adp} py=${want}`);
    }
    if (p.pool_rank !== e.pool_rank[p.player_id]) {
      mismatches.push(`${p.player_id} rank: js=${p.pool_rank} py=${e.pool_rank[p.player_id]}`);
    }
  });
  check(`[${label}] every adjusted ADP and pool rank matches Python exactly`,
    mismatches.length === 0 && adj.length === Object.keys(e.adjusted_adp).length,
    mismatches.slice(0, 5).join('; ') || `count js=${adj.length} py=${Object.keys(e.adjusted_adp).length}`);
});

// --- behaviours the vectors alone would not pin down ------------------------

// Removing one keeper must shift EVERY downstream pick, not just that team's.
{
  const c = V.cases[0];
  const before = K.buildTruePickOrder(c.cfg, c.keepers);
  const trimmed = JSON.parse(JSON.stringify(c.keepers));
  trimmed['1'] = trimmed['1'].slice(1);          // team 1 keeps one fewer
  const after = K.buildTruePickOrder(c.cfg, trimmed);
  check('removing one keeper adds a pick to the draft',
    after.picks.length === before.picks.length + 1,
    `${before.picks.length} -> ${after.picks.length}`);
  check('removing another team\'s keeper still moves MY pick numbers',
    JSON.stringify(after.my_picks) !== JSON.stringify(before.my_picks),
    `${before.my_picks} vs ${after.my_picks}`);
}

// The roll-forward rule for two keepers costing the same round is easy to lose
// in a port and would quietly shift everything after it.
{
  const cfg = { teams: 10, rounds: 8, draft_type: 'snake', roster_size: 11,
                my_draft_slot: 1, adp_blend_weight: 0.7,
                keepers: { count: 2, cost_model: 'original_round', undrafted_round: 10 } };
  const o = K.buildTruePickOrder(cfg, { 3: [{ player_id: 'a', original_round: 2 },
                                            { player_id: 'b', original_round: 2 }] });
  const rounds = o.forfeited.map(f => f.cost_round).sort();
  check('two keepers on the same round roll forward instead of colliding',
    JSON.stringify(rounds) === '[2,3]', JSON.stringify(rounds));
}

// Changing only the slot must not change the pick SEQUENCE, only ownership.
{
  const c = V.cases[0];
  const a = K.buildTruePickOrder(Object.assign({}, c.cfg, { my_draft_slot: 2 }), c.keepers);
  const b = K.buildTruePickOrder(Object.assign({}, c.cfg, { my_draft_slot: 9 }), c.keepers);
  check('a slot change leaves the pick sequence identical',
    JSON.stringify(a.picks.map(p => p.overall)) === JSON.stringify(b.picks.map(p => p.overall)));
  check('a slot change does change which picks are mine',
    JSON.stringify(a.my_picks) !== JSON.stringify(b.my_picks));
  check('runtime slot change equals a rebuild at that slot',
    JSON.stringify(a.my_picks) === JSON.stringify(
      a.picks.filter(p => p.team_slot === 2).map(p => p.overall)));
}

// Python's round() is banker's rounding. Naive JS rounding diverges on ties.
check('round2 matches Python banker\'s rounding on exact ties',
  K.round2(2.675) === 2.68 || K.round2(2.675) === 2.67,   // representable-dependent
  String(K.round2(2.675)));
check('round2(0.125) ties to even like Python', K.round2(0.125) === 0.12, String(K.round2(0.125)));

console.log(`\n${pass}/${pass + fail} keeper parity checks passed`);
process.exit(fail ? 1 : 0);
