'use strict';
const os=require('os'),fs=require('fs'),path=require('path');const ROOT=require('path').join(__dirname,'..','..');
process.env.DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'adv-'));
const store=require(path.join(ROOT,'src','store'));store.initFiles();
const data=require(path.join(ROOT,'src','data'));const {hashPassword}=require(path.join(ROOT,'src','auth'));
const {createApp}=require(path.join(ROOT,'server-app'));const SB=require(path.join(ROOT,'src','sidebets'));
const cookieFrom=r=>r.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ');
let pass=0,fail=0;const ck=(n,c,d)=>{c?(pass++,console.log('PASS '+n)):(fail++,console.log('FAIL '+n+(d?' -> '+d:'')))};
(async function(){
  await data.ensureSeeded();const owners=await store.get('owners');
  const cory=owners.find(o=>o.username==='cory');const rich=owners.find(o=>o.name==='Richard');
  ck('Cory is commissioner',!!cory.is_commissioner);ck('Richard is NOT commissioner',!rich.is_commissioner);
  for(const o of [cory,rich]){o.password_hash=hashPassword('pw');o.must_change_password=false;}await store.set('owners',owners);
  const server=createApp().listen(0);await new Promise(r=>server.once('listening',r));const b=`http://127.0.0.1:${server.address().port}`;
  const login=async u=>cookieFrom(await fetch(b+'/login',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:`username=${u}&password=pw`,redirect:'manual'}));
  const cc=await login('cory');const rc=await login(rich.username);
  const post=async(p,ck,body)=>fetch(b+p,{method:'POST',headers:{Cookie:ck,'Content-Type':'application/x-www-form-urlencoded'},body,redirect:'manual'});
  const get=async(p,ck)=>{const r=await fetch(b+p,{headers:{Cookie:ck},redirect:'manual'});return r.status===200?await r.text():''};
  await post('/sidebets',cc,`format=pool&party=${rich.id}&stake=100&terms=Champion+pool&pool_outcome=holds+the+champion`);
  let bet=(await SB.all()).find(x=>x.format==='pool');
  await post(`/sidebets/${bet.id}/accept`,rc,'');
  const coryView=await get('/bank?section=sidebets',cc);
  const richView=await get('/bank?section=sidebets',rc);
  ck('commissioner (Cory) SEES the pick advisor',/Your advisor/.test(coryView));
  ck('advisor is HONEST: odds pending, no measured model yet',/odds pending/.test(coryView));
  ck('advisor shows NO fabricated Live P(win) while pending',!/Live P\(win\)/.test(coryView));
  ck('advisor shows NO fabricated percentage while pending',!/Title odds you hold/.test(coryView));
  ck('opponent (Richard, non-commish) does NOT see the advisor',!/Your advisor/.test(richView));
  ck('but Richard DOES see the shared draft room',/on the clock|YOUR PICK|drafted/.test(richView));
  server.close();console.log(`\n${pass} passed, ${fail} failed`);process.exit(fail?1:0);
})().catch(e=>{console.error(e);process.exit(1)});
